
GET http://localhost:5157/api/v1/users HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJiZjgyMjVhOC1jNjBlLTQ0ZTAtOTAyZC1iYzFlM2ZkMDljNTAiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDM2MTA3NjUsImV4cCI6MTcwMzc4MzU2NSwiaWF0IjoxNzAzNjEwNzY1LCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.38f-zy5a5pUEznbefGS49ZLhGd9UTTceo9_R_uimZAk

{}

###

POST http://localhost:5157/api/v1/users HTTP/1.1
content-type: application/json

{
  "firstName": "Admin",
  "lastName": "Man",
  "email": "a@b.com",
  "avatar": "string",
  "password": "string",
  "role": "Admin"
}

###

POST http://localhost:5157/api/v1/auth/login HTTP/1.1
content-type: application/json

{
  "email": "a@b.com",
  "password": "string"
}

###

GET http://localhost:5157/api/v1/auth/profile HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwNTA5NzQzOC04OTgzLTRiY2EtYjExMS1kZjcwNjQzNTYwNmMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMxODIwMzEsImV4cCI6MTcwMzM1NDgzMSwiaWF0IjoxNzAzMTgyMDMxLCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.gq0cY-TglkLQlL2YRfkgH4DhagOR_MGoFIzeNpIkj1o

{}

###

GET http://localhost:5157/api/v1/addresses?ownerid=aab1fe72-a5a6-4f38-badd-eae87b5a9294 HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhYWIxZmU3Mi1hNWE2LTRmMzgtYmFkZC1lYWU4N2I1YTkyOTQiLCJyb2xlIjoiTm9ybWFsIiwibmJmIjoxNzAzNjU4Mzg1LCJleHAiOjE3MDM4MzExODUsImlhdCI6MTcwMzY1ODM4NSwiaXNzIjoiTm91dGFqYSIsImF1ZCI6Ik5vdXRhamFTY3VmZmVkV2Vic3RvcmUifQ.AcMPZFqPTEE8Ursy5Q7AEdb-Kfye2STQIJHeQ0PI3iU

{}

###

GET http://localhost:5157/api/v1/addresses/a54a90f3-e469-4d89-b3e5-177c58f92388 HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhYWIxZmU3Mi1hNWE2LTRmMzgtYmFkZC1lYWU4N2I1YTkyOTQiLCJyb2xlIjoiTm9ybWFsIiwibmJmIjoxNzAzNjU4Mzg1LCJleHAiOjE3MDM4MzExODUsImlhdCI6MTcwMzY1ODM4NSwiaXNzIjoiTm91dGFqYSIsImF1ZCI6Ik5vdXRhamFTY3VmZmVkV2Vic3RvcmUifQ.AcMPZFqPTEE8Ursy5Q7AEdb-Kfye2STQIJHeQ0PI3iU

{}

###

DELETE http://localhost:5157/api/v1/addresses/a54a90f3-e469-4d89-b3e5-177c58f92388 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhYWIxZmU3Mi1hNWE2LTRmMzgtYmFkZC1lYWU4N2I1YTkyOTQiLCJyb2xlIjoiTm9ybWFsIiwibmJmIjoxNzAzNjY4MTc2LCJleHAiOjE3MDM4NDA5NzYsImlhdCI6MTcwMzY2ODE3NiwiaXNzIjoiTm91dGFqYSIsImF1ZCI6Ik5vdXRhamFTY3VmZmVkV2Vic3RvcmUifQ.hNqRoGcQ1uLX20mpezce3t-jpMN-UkTypDQn825BULU

{}

###

POST http://localhost:5157/api/v1/addresses/ HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhYWIxZmU3Mi1hNWE2LTRmMzgtYmFkZC1lYWU4N2I1YTkyOTQiLCJyb2xlIjoiTm9ybWFsIiwibmJmIjoxNzAzNjExMTQ4LCJleHAiOjE3MDM3ODM5NDgsImlhdCI6MTcwMzYxMTE0OCwiaXNzIjoiTm91dGFqYSIsImF1ZCI6Ik5vdXRhamFTY3VmZmVkV2Vic3RvcmUifQ.fXoraggCzR5-EvR8mTAy8pyEkh-EfY9dHwBD8Z6zsHc

{
  "userID": "3a597561-64ae-4293-a120-099740e9b803",
  "street": "Some street",
  "zipcode": "12345",
  "city": "Some city",
  "country": "Some country"
}

###

POST http://localhost:5157/api/v1/categories/ HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwNTA5NzQzOC04OTgzLTRiY2EtYjExMS1kZjcwNjQzNTYwNmMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMxODIwMzEsImV4cCI6MTcwMzM1NDgzMSwiaWF0IjoxNzAzMTgyMDMxLCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.gq0cY-TglkLQlL2YRfkgH4DhagOR_MGoFIzeNpIkj1o

{
  "name": "Shoes",
  "url": "https://picsum.photos/200"
}

###

PATCH http://localhost:5157/api/v1/categories/3b221500-59c6-4607-82fb-6ce84e20450d HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJiZjgyMjVhOC1jNjBlLTQ0ZTAtOTAyZC1iYzFlM2ZkMDljNTAiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDM2ODkyNjIsImV4cCI6MTcwMzg2MjA2MiwiaWF0IjoxNzAzNjg5MjYyLCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.SjeLO_t7fuA0NtZXpnXLUsDCXBquwu4fnUQxQw5PA_I

{
  "name": null,
  "url": "https://picsum.photos/200"
}

###

POST http://localhost:5157/api/v1/products/ HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJiZjgyMjVhOC1jNjBlLTQ0ZTAtOTAyZC1iYzFlM2ZkMDljNTAiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDM2ODkyNjIsImV4cCI6MTcwMzg2MjA2MiwiaWF0IjoxNzAzNjg5MjYyLCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.SjeLO_t7fuA0NtZXpnXLUsDCXBquwu4fnUQxQw5PA_I

{
  "title": "Walking shoes",
  "description": "Sit ea ut quis et nostrud nulla quis proident.",
  "price": 10,
  "inventory": 4,
  "categoryID": "3b221500-59c6-4607-82fb-6ce84e20450d",
  "images": [
    {
      "url": "https://picsum.photos/200"
    }
  ]
}

###

PATCH http://localhost:5157/api/v1/products/2cca5210-969c-4d56-9f6f-b2fce3093dd5 HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzYTU5NzU2MS02NGFlLTQyOTMtYTEyMC0wOTk3NDBlOWI4MDMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMyNDM2MzYsImV4cCI6MTcwMzQxNjQzNiwiaWF0IjoxNzAzMjQzNjM2LCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.nflDIUk2JTspdxmm0o0iUZZNaMv7UOYxutf5PIK5vcc

{
  "title": "Crawling shoes"
}

###

GET http://localhost:5157/api/v1/products/ HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwNTA5NzQzOC04OTgzLTRiY2EtYjExMS1kZjcwNjQzNTYwNmMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMxODIwMzEsImV4cCI6MTcwMzM1NDgzMSwiaWF0IjoxNzAzMTgyMDMxLCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.gq0cY-TglkLQlL2YRfkgH4DhagOR_MGoFIzeNpIkj1o

{ }


###

DELETE http://localhost:5157/api/v1/products/3bc9f52f-d6e4-4363-a1d7-29793aac7aea HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwNTA5NzQzOC04OTgzLTRiY2EtYjExMS1kZjcwNjQzNTYwNmMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMxODIwMzEsImV4cCI6MTcwMzM1NDgzMSwiaWF0IjoxNzAzMTgyMDMxLCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.gq0cY-TglkLQlL2YRfkgH4DhagOR_MGoFIzeNpIkj1o

{ }


###

POST http://localhost:5157/api/v1/orders/ HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzYTU5NzU2MS02NGFlLTQyOTMtYTEyMC0wOTk3NDBlOWI4MDMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMyNDM2MzYsImV4cCI6MTcwMzQxNjQzNiwiaWF0IjoxNzAzMjQzNjM2LCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.nflDIUk2JTspdxmm0o0iUZZNaMv7UOYxutf5PIK5vcc

{
  "userID": "3a597561-64ae-4293-a120-099740e9b803",
  "addressID": "c478d6e7-ea28-45ed-b3b4-9d13e6daf62f",
  "orderProducts": [
    {
      "productID": "2cca5210-969c-4d56-9f6f-b2fce3093dd5",
      "amount": 1
    }
  ]
}

###

PATCH http://localhost:5157/api/v1/images/4b50512e-6e5a-4dbb-a097-6a05056ed502 HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzYTU5NzU2MS02NGFlLTQyOTMtYTEyMC0wOTk3NDBlOWI4MDMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMyNDM2MzYsImV4cCI6MTcwMzQxNjQzNiwiaWF0IjoxNzAzMjQzNjM2LCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.nflDIUk2JTspdxmm0o0iUZZNaMv7UOYxutf5PIK5vcc

{
  "url": "string"
}

###