
GET http://localhost:5157/api/v1/users HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzYTU5NzU2MS02NGFlLTQyOTMtYTEyMC0wOTk3NDBlOWI4MDMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMyNjA0NzgsImV4cCI6MTcwMzQzMzI3OCwiaWF0IjoxNzAzMjYwNDc4LCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.CHznkQ0PjzoVyVCr0yG1n-0cASZrnxqgLDrn10mlH2c

{}

###

POST http://localhost:5157/api/v1/users HTTP/1.1
content-type: application/json

{
  "firstName": "Admin",
  "lastName": "Man",
  "email": "a@b.com",
  "avatar": "string",
  "password": "string",
  "role": "Admin"
}

###

POST http://localhost:5157/api/v1/auth/login HTTP/1.1
content-type: application/json

{
  "email": "a@b.com",
  "password": "string"
}

###

GET http://localhost:5157/api/v1/auth/profile HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwNTA5NzQzOC04OTgzLTRiY2EtYjExMS1kZjcwNjQzNTYwNmMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMxODIwMzEsImV4cCI6MTcwMzM1NDgzMSwiaWF0IjoxNzAzMTgyMDMxLCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.gq0cY-TglkLQlL2YRfkgH4DhagOR_MGoFIzeNpIkj1o

{}

###

GET http://localhost:5157/api/v1/addresses HTTP/1.1
content-type: application/json

{}

###

DELETE http://localhost:5157/api/v1/addresses/bdd7b4bd-f4f7-4449-9b2c-a21ad45c7967 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJkNzA0ZGFiYi0yM2M5LTQ2NzYtOTgyNC1kZjU2NDk1NGFhOTUiLCJyb2xlIjoiTm9ybWFsIiwibmJmIjoxNzAzMzMzNzYyLCJleHAiOjE3MDM1MDY1NjIsImlhdCI6MTcwMzMzMzc2MiwiaXNzIjoiTm91dGFqYSIsImF1ZCI6Ik5vdXRhamFTY3VmZmVkV2Vic3RvcmUifQ.8ZSJRDHsaOhIEiQV2dTABI4tIl62I5wSRpRg4AkpfiE

{}

###

POST http://localhost:5157/api/v1/addresses/ HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzYTU5NzU2MS02NGFlLTQyOTMtYTEyMC0wOTk3NDBlOWI4MDMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMyNDM2MzYsImV4cCI6MTcwMzQxNjQzNiwiaWF0IjoxNzAzMjQzNjM2LCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.nflDIUk2JTspdxmm0o0iUZZNaMv7UOYxutf5PIK5vcc

{
  "userID": "3a597561-64ae-4293-a120-099740e9b803",
  "street": "Some other street",
  "zipcode": "12345",
  "city": "Some city",
  "country": "Some country"
}

###

POST http://localhost:5157/api/v1/categories/ HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwNTA5NzQzOC04OTgzLTRiY2EtYjExMS1kZjcwNjQzNTYwNmMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMxODIwMzEsImV4cCI6MTcwMzM1NDgzMSwiaWF0IjoxNzAzMTgyMDMxLCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.gq0cY-TglkLQlL2YRfkgH4DhagOR_MGoFIzeNpIkj1o

{
  "name": "Shoes",
  "url": "https://picsum.photos/200"
}

###

PATCH http://localhost:5157/api/v1/categories/da033fc3-5ad1-42f7-98eb-5816e250f5a9 HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwNTA5NzQzOC04OTgzLTRiY2EtYjExMS1kZjcwNjQzNTYwNmMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMxODIwMzEsImV4cCI6MTcwMzM1NDgzMSwiaWF0IjoxNzAzMTgyMDMxLCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.gq0cY-TglkLQlL2YRfkgH4DhagOR_MGoFIzeNpIkj1o

{
  "name": null,
  "url": "https://picsum.photos/200"
}

###

POST http://localhost:5157/api/v1/products/ HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzYTU5NzU2MS02NGFlLTQyOTMtYTEyMC0wOTk3NDBlOWI4MDMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMyNDM2MzYsImV4cCI6MTcwMzQxNjQzNiwiaWF0IjoxNzAzMjQzNjM2LCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.nflDIUk2JTspdxmm0o0iUZZNaMv7UOYxutf5PIK5vcc

{
  "title": "Jumping shoes",
  "description": "Sit ea ut quis et nostrud nulla quis proident.",
  "price": 10,
  "inventory": 4,
  "categoryID": "da033fc3-5ad1-42f7-98eb-5816e250f5a9",
  "images": [
    {
      "url": "https://picsum.photos/200"
    }
  ]
}

###

PATCH http://localhost:5157/api/v1/products/2cca5210-969c-4d56-9f6f-b2fce3093dd5 HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzYTU5NzU2MS02NGFlLTQyOTMtYTEyMC0wOTk3NDBlOWI4MDMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMyNDM2MzYsImV4cCI6MTcwMzQxNjQzNiwiaWF0IjoxNzAzMjQzNjM2LCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.nflDIUk2JTspdxmm0o0iUZZNaMv7UOYxutf5PIK5vcc

{
  "title": "Crawling shoes"
}

###

GET http://localhost:5157/api/v1/products/ HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwNTA5NzQzOC04OTgzLTRiY2EtYjExMS1kZjcwNjQzNTYwNmMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMxODIwMzEsImV4cCI6MTcwMzM1NDgzMSwiaWF0IjoxNzAzMTgyMDMxLCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.gq0cY-TglkLQlL2YRfkgH4DhagOR_MGoFIzeNpIkj1o

{ }


###

DELETE http://localhost:5157/api/v1/products/3bc9f52f-d6e4-4363-a1d7-29793aac7aea HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwNTA5NzQzOC04OTgzLTRiY2EtYjExMS1kZjcwNjQzNTYwNmMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMxODIwMzEsImV4cCI6MTcwMzM1NDgzMSwiaWF0IjoxNzAzMTgyMDMxLCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.gq0cY-TglkLQlL2YRfkgH4DhagOR_MGoFIzeNpIkj1o

{ }


###

POST http://localhost:5157/api/v1/orders/ HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzYTU5NzU2MS02NGFlLTQyOTMtYTEyMC0wOTk3NDBlOWI4MDMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMyNDM2MzYsImV4cCI6MTcwMzQxNjQzNiwiaWF0IjoxNzAzMjQzNjM2LCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.nflDIUk2JTspdxmm0o0iUZZNaMv7UOYxutf5PIK5vcc

{
  "userID": "3a597561-64ae-4293-a120-099740e9b803",
  "addressID": "c478d6e7-ea28-45ed-b3b4-9d13e6daf62f",
  "orderProducts": [
    {
      "productID": "2cca5210-969c-4d56-9f6f-b2fce3093dd5",
      "amount": 1
    }
  ]
}

###

PATCH http://localhost:5157/api/v1/images/4b50512e-6e5a-4dbb-a097-6a05056ed502 HTTP/1.1
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzYTU5NzU2MS02NGFlLTQyOTMtYTEyMC0wOTk3NDBlOWI4MDMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMyNDM2MzYsImV4cCI6MTcwMzQxNjQzNiwiaWF0IjoxNzAzMjQzNjM2LCJpc3MiOiJOb3V0YWphIiwiYXVkIjoiTm91dGFqYVNjdWZmZWRXZWJzdG9yZSJ9.nflDIUk2JTspdxmm0o0iUZZNaMv7UOYxutf5PIK5vcc

{
  "url": "string"
}

###